theme: jekyll-theme-cayman
repository: skylinespartabots/skylinespartabots.github.io
title: Skyline Spartabots Wiki

markdown: kramdown

sass:
    style: compressed

collections:
    build:
        output: true
        permalink: /:collection/:path
    software:
        output: true
        permalink: /:collection/:path
    electrical:
        output: true
        permalink: /:collection/:path

defaults:
    -
        scope:
            path: ""
            type: "build"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "electrical"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "software"
        values:
            layout: "default"
